version: '2'
services:
  rcgechvalidator:
    build:
      context: ./validateur_api
      dockerfile: Dockerfile
    environment:
      - WS_URI=https://rinkeby.infura.io/v3/3915211d82c546beaf5336b3c9b9b99a
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3,0x3ab05401c0d9483dbeb108b741248bb8e82e323d,0x88ab30749e745a66262275e0489373d3e0781e74
      - TIMEOUT=1653618789,1653618789,1653618789
    working_dir: /app
    command: "/app/api --host 0.0.0.0 --port=8090"
    ports:
      - "0.0.0.0:8090:8090"
      
  webapp:
    build:
      context: ./validateur_webapp
    ports:
      - "0.0.0.0:8001:8080"
    environment:
      - KEY_NAME=myservice # The .cert and .key must have the same name
      - IDP_METADATA=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com/ssorec.geneveid.ch_dgsi_blockchain.xml #Public URL where IdP can be found
      - SP_URL=http://ec2-18-184-234-216.eu-central-1.compute.amazonaws.com:8001 # URL of the service provider
      - API_HOST=rcgechvalidator:8090 # API host, is equal to the <api container name>:<port>
    working_dir: /app
    command: /app/webapp
    volumes:
      - "./myservice.cert:/app/myservice.cert"
      - "./myservice.key:/app/myservice.key"