version: '2'
services:
  rcgechvalidator:
    build: .
    environment:
      - WS_URI=https://rinkeby.infura.io/v3/afeacc980c634655875d915ed65cb0e4
      - LOCKED_ADDR=0x533a245f03a1a46cacb933a3beef752fd8ff45c3,0x3ab05401c0d9483dbeb108b741248bb8e82e323d

  caddy-rev:
    image: abiosoft/caddy
    ports:
      - "0.0.0.0:8002:80"
    volumes:
      - "./Caddyfile:/etc/Caddyfile:ro"
      - "./mockup:/var/www:ro"
