swagger: '2.0'
info:
    title: RCG horodatage - Validateur
    description: |
        RCG horodatage est un service qui permet l'horodatage numérique via
        sur la blockchain Ethereum.
        Le principe est d'envoyer des fichiers qui sont ensuite passer dans
        une fonction hachage SHA3-256. Les « hash » sont ensuite intégrés
        dans un arbre de Merkle dont la racine est inséré dans une
        transaction blockchain, l'(es) adresse(s) signant la transaction
        identifie le Registre du Commerce, c'est une information qui doit
        être publique.
    version: "0.1.0"
produces:
    - application/json
consumes:
    - application/json
paths:
    /status:
        get:
            summary: Retourne des informations variés
            operationId: getStatus
            description: |
                Retourne divers informations par le service
            responses:
                200:
                    description: Information document
                    schema:
                        $ref: '#/definitions/Informations'
                default:
                    description: Internal error
                    schema:
                        $ref: '#/definitions/Error'
definitions:
    Informations:
        type: object
        properties:
            locked_key:
                type: string
    Error:
        type: object
        properties:
            code:
                type: integer
                format: int32
            message:
                type: string
            fields:
                type: string
        required:
            - code
            - message
